Added a GitHub action for checking the build process
aerospike/java-object-mapper pull request #2
Opened 2021-04-18 11:11 UTC by roimenashe

2021-04-18 11:23 UTC, reugn requested changes

2021-04-18 11:23 UTC, reugn commented on .github/build.yml
> +
Add Aerospike DB for integration tests
```yaml
- name: Set up Aerospike Database
  uses: reugn/github-action-aerospike@v1
```

2021-04-18 13:44 UTC, reugn approved these changes

2021-04-19 14:40 UTC, tfaulkes approved these changes

2021-04-19 16:16 UTC, merged